apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumlab-dev-deployment
  namespace: quantumlab-dev
  labels:
    app: quantumlab-dev-deployment
  annotations:
    kubernetes.io/change-cause: "Pipeline updated, job ID: JOB_ID"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantumlab-dev-deployment
  template:
    metadata:
      labels:
        app: quantumlab-dev-deployment
    spec:
      containers:
        - name: quantumlab-dev
          image: projectquantumlab/quantumlab:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          configMap:
            name: dev-env-config
---
apiVersion: v1
kind: Service
metadata:
  name: quantumlab-dev-service
  namespace: quantumlab-dev
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.8.81
spec:
  selector:
    app: quantumlab-dev-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

