FROM ubuntu:jammy
ENV SSL_CERT_DIR=/etc/ssl/certs
WORKDIR /app
COPY /build/backend /app
COPY /build/website /app/dist
RUN chmod +x /app/quantumlab
EXPOSE 8080
ENTRYPOINT ["timeout", "168h", "/app/quantumlab"]