FROM ubuntu:jammy
WORKDIR /app
COPY /build/backend /app
COPY /build/website /app/dist
RUN chmod +x /app/quantumlab
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates
EXPOSE 8080
ENTRYPOINT ["/app/quantumlab"]